function Ergebnislondon = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ERGEBNISLONDON = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  ERGEBNISLONDON = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  Ergebnislondon = importfile("C:\Users\Franziskus\Documents\Uni\M27 Explainable MachineLearning\Seminar\Ergebnisse\Ergebnis-london.jpg.txt", [1, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 16-Jan-2024 10:56:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "string";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName1", "EmptyFieldRule", "auto");

% Import the data
Ergebnislondon = readmatrix(filename, opts);

end